export const test_constants = {
  LOGIN_PAGE_URL: "/Prod/Account/LogIn",
  DASHBOARD_PAGE_URL: "/Prod/Benefits",
  EMPLOYEES_API_URL: "/Prod/api/employees",
  EMPLOYEE_GET_STRUCTURE: {
    partitionKey: "string",
    sortKey: "string",
    username: "string",
    id: "string",
    firstName: "string",
    lastName: "string",
    dependants: "number",
    expiration: "string",
    salary: "number",
    gross: "number",
    benefitsCost: "number",
    net: "number",
  },
  EMPLOYEE_POST_STRUCTURE: {
    partitionKey: "string",
    sortKey: "string",
    username: "string",
    id: "string",
    firstName: "string",
    lastName: "string",
    dependants: "number",
    salary: "number",
    gross: "number",
    benefitsCost: "number",
    net: "number",
  },
};
